#!/usr/bin/env python3

from pathlib import Path
from sys import argv
import shutil
import re

def print_path(path, arg2, arg3):
    if path.is_dir():
        if path.absolute().name == arg2:
            newDirName = re.sub(arg2, arg3, str(path.absolute().name))
            newPath = path.absolute().parent / newDirName
            shutil.copytree(path, newPath)
            shutil.rmtree(path)
            path = newPath
        for entry in path.iterdir():
            print_path(entry, arg2, arg3)

    else: # it is a file
        with open(path.absolute()) as f:
            newText=f.read().replace(arg2, arg3)

        with open(path.absolute(), "w") as f:
            f.write(newText)

        newFile = re.sub(arg2, arg3, str(path.absolute().name))
        # change the file name
        newFilePath = path.absolute().parent / newFile
        if not newFilePath.exists():
            shutil.copy(path.absolute(), path.absolute().parent / newFile)
            path.absolute().unlink()


if len(argv) < 4:
  print('Invalid Usage.')
  print("Proper Usage: ./replace test 'DevOps' 'WebApp'")
  exit(1)

if argv[1] == 'test':
    pstr = argv[1]

    print_path(Path.cwd() / pstr, argv[2], argv[3])

else:
  print('Invalid Usage.')
  print("Proper Usage: ./replace test 'DevOps' 'WebApp'")
  exit(1)

